---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-token
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgBgi/p5T8hBuWP7Gsy1ksxdsb8e0hbpsFbQbka8MR7L69f3/JmfguBl5BTyYHLmLlAK8FnZHKiQTh25CVB3Grm7pnw2kqCtJIRZd/AihOm6DVDsDXd6+vxN/EonqV3LNvZ13LFDvu4iZEkrz3SwP+nQlYaasH85jeg22UmjPd3LFsjOZdHbW2XAI3vu2aFdlK59TnBEQfV1zMYUJ75GqmEMXCybm+Whr7YycmgTp3JY8fw0DSdoRmhSsu61mNyZ0Lpkd4s7ndLkiInFn0FS5HQTAGx5Gjwv5xFD4gdkC/jal3FgSNMYk2nQ0gToQOf4H7FEYpdtnehuvZjUWoDh49MQDZUm3OTuuFBBzD+3+s/zW4rJTFPE8kKpoyYFJu+Ug5zB9kVagG2FnRNxmYx5SQQpLhO9sg1FT4nINsqLNaaNPCm2kN+sBL5GVHZuCrbjzwsUsOt0zdZAzRiDjDa57PjeDMKdTnnOg+N9J3gIebCsx13GC+uubOFbu+sd4Hkogk/fFgalPGKo4CCWWt2AMS4Rvf6F8KqtUFT/YNQFnL8dFc+eA48hwv/wflSURKR6Y4pO/dFiBR0I87R3WGwlaZC6X2acse3Hi/rw8c97OQ6T/M9+kuffE4DhDDyH91nA71MEKEMHeKMfFOZPUk/GDH94OCAPoNI61/uljG9nHWIZaOHo3yaN5zKtDYXaKNqt7VYUhmayFW8n+PFRrCifDIDFRyXH8Z52zleL/G25dP8ZQaYEqkLhkChMlazU5hnGvd/Nhio=
    TOKEN: AgB8YuH9sBhYJnfK39xB2aGi1vhCDBwrr691g7h+44XEEebvzSXj09RlBwbQq1f8Riob5yqyJHmmGfjV9mI82W2DcTqyn6HhTiotkK1Gsal10bgIBU8L6PcZSrhta0kEQz8/WkiEGCPaTgGclCq52TpyXKYS0DLcSJrHHAw+HVcTJw7o6xI3yzovFNS2DMQpoFTrL8S6+nf3T5EP5vM1AWFV+/k8llx7bd/0ypj7v8ckaaBEQt9e8BV/nDyipm5crmWFfxm/HOdCt69LRhyrKtGnY5jy6UH0MLb8pDrcxcQklJnhNndspGfSaBH1akQ9BvI/aw7EO871CXiWI8CmToK5OmzN1TrktzR+WGim0giy0JjeaZZod0aa8YPWH5KkTuu7PZA4NGs6WDfBKuzsEl97ABQiZbG1/iKdIniatypCWZxchLNekCxTv8nq3JCZTivDvKvPoKzIYhCiCrsnJ+V+nal+oskkV6IKOVbkLDT+1yoN0lo3QDsdckVQdRI0LAqDg9J/w7Cy5HYbq8U2sK9KbHkPniuL2CNnXoDVRz4+jdcMOhv8N5eDTRMz9/o6H85QGFnEtxkzTTRVgYhe5xze1ZcIaBpvVxOZX4HWG3sNXVy5sPthy6sW8O7huatATpzEipqLPedsUzOk1Qd9I39ha3LP1zpuTJoJ1B9KmxQ24inEiAP0JSrvD5hYJQOF9Mu61H3l/or/xy9sMavpKUSGVgWy6TbiITq6uD1wqFzBCCQucG8wi/k/an786BjK
  template:
    metadata:
      creationTimestamp: null
      name: secret-token
      namespace: default
    type: Opaque
