version: "3"
services:
  app-mysql:
    image: mysql:latest
    container_name: app-bot-mysql
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./config/mysql:/docker-entrypoint-initdb.d
      - app-mysql-volume:/var/lib/mysql
    healthcheck:
        test: mysqladmin ping -hlocalhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}
        interval: 10s
        retries: 5
  app-redis:
    image: redis:latest
    container_name: app-bot-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  app-mongo:
    image: bitnami/mongodb:4.4.13-debian-10-r30
    container_name: app-bot-mongo
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: mongo --eval "db.adminCommand('ping')" --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
  app-telegram:
    depends_on:
      app-mysql:
        condition: service_healthy
      app-redis:
        condition: service_healthy
      app-mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-bot-telegram
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    restart: always
volumes:
  app-mysql-volume:
