labels:
  app:
    app: triangle-app
  mysql:
    app: triangle-app-mysql

secret:
  type: Opaque
  TOKEN: NjQwNzgyNjQ1MTpBQUV1NlR4MkJWcGh0OEJ2QS15RHRZendpcDNhS1JQc1lQNA==
  MYSQL_ROOT_PASSWORD: dHJpYW5nbGVhcHA=
  MYSQL_PASSWORD: dHJpYW5nbGVhcHA=
  CHAT_ID_SOPORTE: NTkwNTQxMTc5

configmap:
  URL_WEBHOOK: "https://bot.rafaeltorices.com"
  TITULO_APP: TRIANGLE_APP
  TELEFONO_SOPORTE: 123456789
  EMAIL_SOPORTE:
  MYSQL_PORT: 3306
  MYSQL_DATABASE: triangleapp
  MYSQL_USER: triangleapp
  API_TELEGRAM: "https://api.telegram.org/bot"

deployment:
  replicaCount: 2
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70
  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 100Mi
      cpu: 120m
  app:
    ports:
      name: app-port
      containerPort: 5000
  mysql:
    ports:
      name: mysql-port
      containerPort: 3306
    volumeClaimTemplates:
      storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storageSize: 1Gi
      volumeMode: Filesystem

image:
  repository:
    app: kctriangle/triangle-bot
    mysql: mysql
  tag:
    app: latest
    mysql: latest

service:
  app:
    type: ClusterIP
    ports:
      name: app-port
      port: 5000
      targetPort: app-port
      protocol: TCP
  mysql:
    type: ClusterIP
    ports:
      name: mysql-port
      port: 3306
      targetPort: mysql-port
      protocol: TCP

serviceAccount:
  create: false
  annotations: {}
  name: ""

ingress:
  enabled: true
  class: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    host: bot.rafaeltorices.com
    paths:
      path: /
  ports:
    number: 5000
  tls:
    enabled: false

statefulset:
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 512Mi
