apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "triangle-app.fullname" . }}-mongo-statefulset
spec:
  serviceName: {{ include "triangle-app.fullname" . }}-mongo-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "triangle-app.selectorLabels" . | nindent 6 }}
      app: {{ .Values.labels.mongo.app }}
  template:
    metadata:
      labels:
        {{- include "triangle-app.selectorLabels" . | nindent 8 }}
        app: {{ .Values.labels.mongo.app }}
    spec:
      containers:
        - name: triangle-app-mongo
          image: {{ .Values.image.repository.mongo }}:{{ .Values.image.tag.mongo }}
          ports:
            - name: {{ .Values.deployment.mongo.ports.name }}
              containerPort: {{ .Values.deployment.mongo.ports.containerPort }}
          resources:
            {{- toYaml .Values.statefulset.resources | nindent 12 }}
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "triangle-app.fullname" . }}-configmap
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "triangle-app.fullname" . }}-configmap
                  key: MONGO_PORT
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "triangle-app.fullname" . }}-configmap
                  key: MONGO_DATABASE
            - name: MONGO_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "triangle-app.fullname" . }}-configmap
                  key: MONGO_COLLECTION
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mongo --eval "db.adminCommand('ping')" --quiet | grep 1
          volumeMounts:
            # - name: {{ include "triangle-app.fullname" . }}-mongo-volume
            #   mountPath: /var/lib/mongodb
  # volumeClaimTemplates:
  #   - metadata:
  #       name: {{ include "triangle-app.fullname" . }}-mongo-volume
  #     spec:
  #       accessModes: {{ .Values.deployment.mongo.volumeClaimTemplates.accessModes }}
  #       storageClassName: {{ .Values.deployment.mongo.volumeClaimTemplates.storageClassName }}
  #       resources:
  #         requests:
  #           storage: {{ .Values.deployment.mongo.volumeClaimTemplates.resources.requests.storageSize }}
  #       volumeMode: {{ .Values.deployment.mongo.volumeClaimTemplates.volumeMode }}
