apiVersion: v1
kind: Secret
metadata:
  name: {{ include "triangle-app.fullname" . }}-secret
type: {{.Values.secret.type }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD | indent 4 }}
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD | indent 4 }}
  TOKEN: {{ .Values.secret.TOKEN | indent 4 }}