apiVersion: v1
kind: Secret
metadata:
  name: {{ include "triangle-app.fullname" . }}-secret
type: {{.Values.secret.type }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD | indent 4 }}
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD | indent 4 }}
  CHAT_ID_SOPORTE: {{ .Values.secret.CHAT_ID_SOPORTE | indent 4 }}
  WEB_PASSWORD: {{ .Values.secret.WEB_PASSWORD | indent 4 }}