apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "triangle-app.fullname" . }}-mysql-statefulset
spec:
  serviceName: {{ include "triangle-app.fullname" . }}-mysql-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "triangle-app.selectorLabels" . | nindent 6 }}
      app: {{ .Values.labels.mysql.app }}
  template:
    metadata:
      labels:
        {{- include "triangle-app.selectorLabels" . | nindent 8 }}
        app: {{ .Values.labels.mysql.app }}
    spec:
      containers:
        - name: triangle-app-mysql
          image: {{ .Values.image.repository.mysql }}:{{ .Values.image.tag.mysql }}
          ports:
            - name: {{ .Values.deployment.mysql.ports.name }}
              containerPort: {{ .Values.deployment.mysql.ports.containerPort }}
          resources:
            {{- toYaml .Values.statefulset.resources | nindent 12 }}
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "triangle-app.fullname" . }}-configmap
                  key: MYSQL_HOST
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "triangle-app.fullname" . }}-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                    name: {{ include "triangle-app.fullname" . }}-configmap
                    key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                    name: {{ include "triangle-app.fullname" . }}-configmap
                    key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: {{ include "triangle-app.fullname" . }}-secret
                    key: MYSQL_PASSWORD
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                    name: {{ include "triangle-app.fullname" . }}-configmap
                    key: MYSQL_PORT
          volumeMounts:
            - name: {{ include "triangle-app.fullname" . }}-mysql-volume
              mountPath: /var/lib/mysql
            - name: {{ include "triangle-app.fullname" . }}-mysql-init-configmap
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: {{ include "triangle-app.fullname" . }}-mysql-init-configmap
          configMap:
            name: {{ include "triangle-app.fullname" . }}-mysql-init-configmap
            items:
              - key: db.sql
                path: db.sql
  volumeClaimTemplates:
    - metadata:
        name: {{ include "triangle-app.fullname" . }}-mysql-volume
      spec:
        accessModes: {{ .Values.deployment.mysql.volumeClaimTemplates.accessModes }}
        storageClassName: {{ .Values.deployment.mysql.volumeClaimTemplates.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.deployment.mysql.volumeClaimTemplates.resources.requests.storageSize }}
        volumeMode: {{ .Values.deployment.mysql.volumeClaimTemplates.volumeMode }}
