apiVersion: v1
kind: Service
metadata:
  name: {{ include "triangle-app.fullname" . }}-mongo-headless
  labels:
    {{- include "triangle-app.labels" . | nindent 4 }}
    app: {{ .Values.labels.mongo.app }}
spec:
  ports:
    - port: {{ .Values.service.mongo.ports.port }}
      targetPort: {{ .Values.service.mongo.ports.targetPort }}
      protocol: {{ .Values.service.mongo.ports.protocol }}
      name: {{ .Values.service.mongo.ports.name }}
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "triangle-app.selectorLabels" . | nindent 4 }}
    app: {{ .Values.labels.mongo.app }}
