{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "triangle-app.fullname" . }}-sa
  labels:
    {{- include "triangle-app.labels" . | nindent 4 }}
{{- end }}
