apiVersion: v1
kind: Service
metadata:
  name: {{ include "triangle-app.fullname" . }}-mysql-service
  labels:
    {{- include "triangle-app.labels" . | nindent 4 }}
    app: {{ .Values.labels.mysql.app }}
spec:
  type: {{ .Values.service.mysql.type }}
  ports:
    - port: {{ .Values.service.mysql.ports.port }}
      targetPort: {{ .Values.service.mysql.ports.targetPort }}
      protocol: {{ .Values.service.mysql.ports.protocol }}
      name: {{ .Values.service.mysql.ports.name }}
  selector:
    {{- include "triangle-app.selectorLabels" . | nindent 4 }}
    app: {{ .Values.labels.mysql.app }}