apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triangle-app-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KeepDevOpsTriangel/Keep-DevOps-Triangel-app
    targetRevision: HEAD
    path: manifest
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
