# Values file for ArgoCD configuration in the cluster by Helm chart
configs:
  params:
    server.insecure: false
  cm:
    resource.compareoptions: |
      ignoreAggregatedRoles: true
      ignoreResourceStatusField: all
    url: https://argocdtriangleapp.rafaeltorices.com/argocd
    application.instanceLabelKey: argocd.argoproj.io/instance
server:
  insecure: true
  extraArgs:
    - --rootpath
    - /argocd
  ingress:
    ingressClassName: nginx
    annotations:
      # cert-manager.io/cluster-issuer: ca-issuer
      cert-manager.io/issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    enabled: true
    rules:
      - host: argocdtriangleapp.rafaeltorices.com
        http:
          paths:
            - path: /argocd
              pathType: Prefix
              backend:
                service:
                  name: triangle-app-argocd-server
                  port:
                    number: 443
    tls:
      - hosts:
          - argocdtriangleapp.rafaeltorices.com
        secretName: argocd-secret-tls
