# Values file for ArgoCD configuration in the cluster by Helm chart
configs:
  params:
    server.insecure: true
  cm:
    resource.compareoptions: |
      ignoreAggregatedRoles: true
      ignoreResourceStatusField: all
    url: http://localhost/argocd
    application.instanceLabelKey: argocd.argoproj.io/instance
server:
  insecure: true
  extraArgs:
    - --rootpath
    - /argocd
  ingress:
    ingressClassName: nginx
    annotations:
      # cert-manager.io/cluster-issuer: ca-issuer
      cert-manager.io/issuer: "letsencrypt-prod"
    enabled: true
    rules:
      - host: argodemo.rafaeltorices.com
        http:
          paths:
            - path: /argocd
              pathType: Prefix
              backend:
                service:
                  name: argocd-server
                  port:
                    number: 443
    tls:
      - hosts:
          - argodemo.rafaeltorices.com
        secretName: argocd-secret-tls
