name: Generate Documentation

on:
  push:
    branches:
      - 'albert'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install and verify dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip list

      - name: Generate Documentation
        run: |
          pwd
          mkdir docs
          pdoc -o docs src/application
        working-directory: ./app

      - name: Archive Documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: ./app/docs  # Ajusta la ruta según tu estructura
