name: Generate Documentation

on:
  push:
    branches:
      - 'albert'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pdoc
        run: |
          python -m pip install pdoc

      - name: Generate Documentation
        run: |
          mkdir docs
          pdoc --html -o docs src/application

      - name: Archive Documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: ./docs
