name: Testing

on:
  pull_request:
    branches:
      - 'albert'
  push:
    branches:
      - 'albert'

jobs:
  testing-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pdoc3
        working-directory: ./app  # Corregido el working-directory

      - name: Run tests and generate coverage report
        run: |
          coverage run -m pytest app
          coverage report -m

      - name: Run Pylint
        run: |
          pylint --fail-under=1.0 app
        working-directory: ./app

      - name: Clean existing docs
        run: rm -rf docs
        continue-on-error: true  # Continuar si el directorio no existe

      - name: Generate Documentation
        run: |
          mkdir docs
          pdoc3 --html -o docs src
        working-directory: ./app
