name: Testing and Documentation

on:
  pull_request:
    branches:
      - 'albert'
  push:
    branches:
      - 'albert'

jobs:
  testing-and-docs:
    runs-on: ubuntu-latest

    jobs:
      - name: Testing
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8

          - name: Install and verify dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r app/requirements.txt
              pip list

          - name: Run tests and generate coverage report
            run: |
              coverage run -m pytest app
              coverage report -m

          - name: Run Pylint
            run: |
              pylint --fail-under=1.0 app

      - name: Generate Documentation
        needs: testing
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8

          - name: Install and verify dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r app/requirements.txt
              pip list

          - name: Generate and Archive Documentation
            run: |
              rm -rf docs
              mkdir docs
              pdoc -o docs src/application
              mv docs ../  # Mover la carpeta docs al directorio principal
            working-directory: ./app

          - name: Archive Documentation
            uses: actions/upload-artifact@v2
            with:
              name: documentation
              path: ./docs  # Ruta ajustada después de mover la carpeta
